spring:
  application:
    name: devApp
  datasource:
    url: jdbc:mysql://localhost:3306/*
    username: *
    password: *
  jpa:
    hibernate:
      ddl-auto: update
  app:
    jwtExpirationMs: 172800000
  mail:
    host: smtp.gmail.com
    port: 587
    username: *
    password: *
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


frontend:
  url: "http://localhost:5173"

#  security:
#    user:
#      name: user
#      password: user
